### ISSUE TITLE
I can't use my image as an input.

### ISSUE THREAD

**Issue by mrKornWij** [mogvision/FFD#8]
It seems that If I want to use my image i need to turn image into .txt file but I don't know how to do it. please suggest me! thank you

**Comment by 1061700625** [comment]
你需要自己建一个空的txt文件，我估计他的FFD会写进去，但由于不是r+模式，所以不会自动创建该文件。我已经测试了，手动创建txt文件后再运行，确实有效。

machine translation ：
You will need to create an empty TXT file, which I expect will be written in by FFD, but since it is not in r+ mode, it will not be created automatically.  I have tested, manually create TXT file and then run, it does work.

**Comment by 1061700625** [comment]
你需要自己建一个空的txt文件，我估计他的FFD会写进去，但由于不是w+模式，所以不会自动创建该文件。我已经测试了，手动创建txt文件后再运行，确实有效。

machine translation ：
You will need to create an empty TXT file, which I expect will be written in by FFD, but since it is not in w+ mode, it will not be created automatically. I have tested, manually create TXT file and then run, it does work.

**Comment by 1061700625** [comment]
./FFD: error while loading shared libraries: libopencv_calib3d.so.3.2: cannot open shared object file: No such file or directory

1、他的txt文件应该是由FFD程序创建的，如果没有生成，那说明FFD执行出错了。我直接运行FFD，发现确实报错了。可能是作者用到了OpenCV3.2来编译，而我电脑上装的是4.5版本，只有libopencv_calib3d.so.4.5。按照作者写的，我重新下载了3.2.0版本并编译。
2、“Ubuntu下多版本OpenCV共存和切换” 可参考：https://blog.csdn.net/learning_tortosie/article/details/80594399。如果遇到安装3.2报错，可参考：https://blog.csdn.net/goodxin_ie/article/details/82856008
3、安装完成后，参考这个issue添加路径：cggos/cvkit#1。
4、亲测可用~

**Comment by 1061700625** [comment]
整理了下：https://xfxuezhang.blog.csdn.net/article/details/121159824
